# Generated by Django 5.0 on 2024-01-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarlaTakipAfterLogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseladd',
            name='gubre_fiyat',
        ),
        migrations.RemoveField(
            model_name='parseladd',
            name='surulme_fiyat',
        ),
        migrations.RemoveField(
            model_name='parseladd',
            name='tohum_fiyat',
        ),
        migrations.AddField(
            model_name='parseladd',
            name='gubre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parseladd',
            name='surulme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parseladd',
            name='tohum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parseladd',
            name='tarla_adi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
