# Generated by Django 5.0 on 2024-01-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarlaTakipAfterLogin', '0002_remove_parseladd_gubre_fiyat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseladd',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parseladd',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
