# Generated by Django 5.0 on 2024-01-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarlaTakipAfterLogin', '0003_parseladd_purchase_price_parseladd_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseladd',
            name='ekilen_urun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
